slam_toolbox:
  ros__parameters:
    mode: mapping
    scan_topic: /scan
    map_frame: map
    base_frame: base_link
    odom_frame: odom
    provide_odom_frame: false    # we publish odom->base_link
    publish_tf: false            # we already publish TF
    use_odometry: true
    use_scan_matching: true

    minimum_travel_distance: 0.005
    minimum_travel_rotation: 0.005
    minimum_time_interval: 0.05

    resolution: 0.05
    map_publish_period: 0.2
    transform_publish_period: 0.05
    queue_size: 500
